# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost_multiplier', models.FloatField()),
                ('experience_gain', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('buy_cost', models.IntegerField()),
            ],
        ),
    ]
