# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShipUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item_required', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
                ('ship_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ShipStore')),
            ],
        ),
    ]
