# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_island_porttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Level')),
            ],
        ),
        migrations.DeleteModel(
            name='PortType',
        ),
    ]
