# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 22:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20161203_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipupgrade',
            name='item_required',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
        ),
    ]
