# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161203_2258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shipupgrade',
            unique_together=set([('ship_store', 'item_required')]),
        ),
    ]
