# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 08:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_auto_20161203_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipupgrade',
            old_name='item_required',
            new_name='item_id',
        ),
        migrations.AlterField(
            model_name='shipupgrade',
            name='ship_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_required',
                                    to='core.ShipStore'),
        ),
        migrations.AlterUniqueTogether(
            name='shipupgrade',
            unique_together=set([('ship_store', 'item_id')]),
        ),
    ]
