# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_auto_20161204_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('is_essential', models.BooleanField(default=False)),
            ],
        ),
    ]
