# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='habitable',
            field=models.BooleanField(default=True),
        ),
    ]
