# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161213_1634'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shipstore',
            managers=[
            ],
        ),
    ]
