# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 11:02
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20161222_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipstore',
            name='image',
            field=models.ImageField(upload_to=core.models.upload_ship_image),
        ),
    ]
