# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170303_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipstore',
            name='ship_id',
            field=models.IntegerField(default=0),
        ),
    ]
