# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_auto_20170303_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='dock',
            name='status',
            field=models.CharField(default='locked', max_length=10),
        ),
        migrations.AddField(
            model_name='shipstore',
            name='ship_id',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='gold',
            field=models.IntegerField(default=0),
        ),
    ]
