# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_shipstore_ship_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipstore',
            name='ship_id',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
