# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170306_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipstore',
            old_name='ship_id',
            new_name='ship_lvl',
        ),
    ]
