# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port', to='ship.PortType'),
        ),
        migrations.AlterField(
            model_name='port',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ship',
            name='upgrade_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ship.Ship'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='upgraded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
