# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0002_auto_20161205_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dock',
            name='ship',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ship.Ship'),
        ),
    ]
