# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0003_auto_20161210_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='raid_count',
            field=models.IntegerField(default=0),
        ),
    ]
