# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0004_auto_20161210_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockchart',
            name='end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dockchart',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
