# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0005_auto_20161210_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='log',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ship.DockChart'),
        ),
    ]
