# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0008_port_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='porttype',
            name='penalizable',
            field=models.BooleanField(default=True),
        ),
    ]
