# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0009_porttype_penalizable'),
    ]

    operations = [
        migrations.AddField(
            model_name='porttype',
            name='ownable',
            field=models.BooleanField(default=True),
        ),
    ]
