# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0010_porttype_ownable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dock',
            name='ship',
        ),
        migrations.RemoveField(
            model_name='dock',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='dock',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dockchart',
            name='port',
        ),
        migrations.RemoveField(
            model_name='dockchart',
            name='ship',
        ),
        migrations.RemoveField(
            model_name='finelog',
            name='dock_chart',
        ),
        migrations.RemoveField(
            model_name='port',
            name='log',
        ),
        migrations.RemoveField(
            model_name='port',
            name='type',
        ),
        migrations.RemoveField(
            model_name='port',
            name='user',
        ),
        migrations.RemoveField(
            model_name='revenuelog',
            name='dock_chart',
        ),
        migrations.RemoveField(
            model_name='revenuelog',
            name='item',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='ship_store',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='upgrade_to',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dock',
        ),
        migrations.DeleteModel(
            name='DockChart',
        ),
        migrations.DeleteModel(
            name='FineLog',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.DeleteModel(
            name='PortType',
        ),
        migrations.DeleteModel(
            name='RevenueLog',
        ),
        migrations.DeleteModel(
            name='Ship',
        ),
    ]
