# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20161204_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gcm_token',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
