# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20161210_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(default=10),
        ),
    ]
