# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_auto_20161222_1050'),
        ('player', '0008_auto_20161222_0839'),
    ]

    operations = [
    ]
