# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
