# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20170226_0223'),
        ('player', '0011_auto_20170221_0003'),
    ]

    operations = [
    ]
