# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_merge_20170226_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
