# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=12),
        ),
    ]
