# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_auto_20170228_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 3, 4, 13, 31, 4, 160904, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
