# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_profile_last_seen'),
        ('player', '0015_profile_cumulative_ship_level'),
    ]

    operations = [
    ]
